# coding: utf-8

# flake8: noqa

"""
    Ramalama-Worker REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "WorkerApiApi",
    "WorkerProxyApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AvailableModelDTO",
    "Error",
    "InferenceOptionsDTO",
    "ModelServeRequestDTO",
    "ModelServeResponseDTO",
    "ModelStopRequestDTO",
    "PaginationMetadata",
    "ServeOptionsDTO",
]

# import apis into sdk package
from daemon.client.worker.api.worker_api_api import WorkerApiApi as WorkerApiApi
from daemon.client.worker.api.worker_proxy_api import WorkerProxyApi as WorkerProxyApi

# import ApiClient
from daemon.client.worker.api_response import ApiResponse as ApiResponse
from daemon.client.worker.api_client import ApiClient as ApiClient
from daemon.client.worker.configuration import Configuration as Configuration
from daemon.client.worker.exceptions import OpenApiException as OpenApiException
from daemon.client.worker.exceptions import ApiTypeError as ApiTypeError
from daemon.client.worker.exceptions import ApiValueError as ApiValueError
from daemon.client.worker.exceptions import ApiKeyError as ApiKeyError
from daemon.client.worker.exceptions import ApiAttributeError as ApiAttributeError
from daemon.client.worker.exceptions import ApiException as ApiException

# import models into sdk package
from daemon.client.worker.models.available_model_dto import AvailableModelDTO as AvailableModelDTO
from daemon.client.worker.models.error import Error as Error
from daemon.client.worker.models.inference_options_dto import InferenceOptionsDTO as InferenceOptionsDTO
from daemon.client.worker.models.model_serve_request_dto import ModelServeRequestDTO as ModelServeRequestDTO
from daemon.client.worker.models.model_serve_response_dto import ModelServeResponseDTO as ModelServeResponseDTO
from daemon.client.worker.models.model_stop_request_dto import ModelStopRequestDTO as ModelStopRequestDTO
from daemon.client.worker.models.pagination_metadata import PaginationMetadata as PaginationMetadata
from daemon.client.worker.models.serve_options_dto import ServeOptionsDTO as ServeOptionsDTO

