# coding: utf-8

# flake8: noqa
"""
    Ramalama-Worker REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from daemon.client.worker.models.available_model_dto import AvailableModelDTO
from daemon.client.worker.models.error import Error
from daemon.client.worker.models.inference_options_dto import InferenceOptionsDTO
from daemon.client.worker.models.model_serve_request_dto import ModelServeRequestDTO
from daemon.client.worker.models.model_serve_response_dto import ModelServeResponseDTO
from daemon.client.worker.models.model_stop_request_dto import ModelStopRequestDTO
from daemon.client.worker.models.pagination_metadata import PaginationMetadata
from daemon.client.worker.models.serve_options_dto import ServeOptionsDTO

