# coding: utf-8

# flake8: noqa

"""
    Ramalama-Daemon REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DaemonApiApi",
    "DaemonWebApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AvailableModelDTO",
    "Error",
    "InferenceOptionsDTO",
    "ModelServeRequestDTO",
    "ModelServeResponseDTO",
    "ModelStopRequestDTO",
    "PaginationMetadata",
    "RegisteredWorkerDTO",
    "ServeOptionsDTO",
    "WorkerRegistrationDTO",
]

# import apis into sdk package
from worker.client.daemon.api.daemon_api_api import DaemonApiApi as DaemonApiApi
from worker.client.daemon.api.daemon_web_api import DaemonWebApi as DaemonWebApi

# import ApiClient
from worker.client.daemon.api_response import ApiResponse as ApiResponse
from worker.client.daemon.api_client import ApiClient as ApiClient
from worker.client.daemon.configuration import Configuration as Configuration
from worker.client.daemon.exceptions import OpenApiException as OpenApiException
from worker.client.daemon.exceptions import ApiTypeError as ApiTypeError
from worker.client.daemon.exceptions import ApiValueError as ApiValueError
from worker.client.daemon.exceptions import ApiKeyError as ApiKeyError
from worker.client.daemon.exceptions import ApiAttributeError as ApiAttributeError
from worker.client.daemon.exceptions import ApiException as ApiException

# import models into sdk package
from worker.client.daemon.models.available_model_dto import AvailableModelDTO as AvailableModelDTO
from worker.client.daemon.models.error import Error as Error
from worker.client.daemon.models.inference_options_dto import InferenceOptionsDTO as InferenceOptionsDTO
from worker.client.daemon.models.model_serve_request_dto import ModelServeRequestDTO as ModelServeRequestDTO
from worker.client.daemon.models.model_serve_response_dto import ModelServeResponseDTO as ModelServeResponseDTO
from worker.client.daemon.models.model_stop_request_dto import ModelStopRequestDTO as ModelStopRequestDTO
from worker.client.daemon.models.pagination_metadata import PaginationMetadata as PaginationMetadata
from worker.client.daemon.models.registered_worker_dto import RegisteredWorkerDTO as RegisteredWorkerDTO
from worker.client.daemon.models.serve_options_dto import ServeOptionsDTO as ServeOptionsDTO
from worker.client.daemon.models.worker_registration_dto import WorkerRegistrationDTO as WorkerRegistrationDTO

