# coding: utf-8

# flake8: noqa
"""
    Ramalama-Daemon REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from worker.client.daemon.models.available_model_dto import AvailableModelDTO
from worker.client.daemon.models.error import Error
from worker.client.daemon.models.inference_options_dto import InferenceOptionsDTO
from worker.client.daemon.models.model_serve_request_dto import ModelServeRequestDTO
from worker.client.daemon.models.model_serve_response_dto import ModelServeResponseDTO
from worker.client.daemon.models.model_stop_request_dto import ModelStopRequestDTO
from worker.client.daemon.models.pagination_metadata import PaginationMetadata
from worker.client.daemon.models.registered_worker_dto import RegisteredWorkerDTO
from worker.client.daemon.models.serve_options_dto import ServeOptionsDTO
from worker.client.daemon.models.worker_registration_dto import WorkerRegistrationDTO

